name: KiCad CI

on:
  push:
  pull_request:

jobs:
  kicad:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install KiCad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
          sudo apt update
          sudo apt install -y kicad

      - name: Run DRC
        run: |
          kicad-cli pcb drc board.kicad_pcb \
            --output drc_report.json

      - name: Export Gerbers
        run: |
          kicad-cli pcb export gerbers board.kicad_pcb \
            --output gerbers/

# TODO
      - name: Run KiCAD CLI script
        run: |
          chmod +x scripts/export.sh
          scripts/export.sh

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: kicad-outputs
          path: output/